version = 1

test_patterns = ["**/test/**"]

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "19"
  language_version = "1.9"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "terraform"