quarkus.devservices.enabled=false

quarkus.ssm.endpoint-override=http://localhost:4566
quarkus.ssm.aws.credentials.type=static
quarkus.ssm.aws.credentials.static-provider.access-key-id=fake
quarkus.ssm.aws.credentials.static-provider.secret-access-key=fake